language: node_js
node_js:
  - 8

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - yarn build

# before_deploy:
#   - mkdir -p deploy/client
#   - mv kobobook-webservice-api * deploy/client/kobobook-webservice-api.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kobobook-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    # local_dir: deploy
    wait-until-deployed: true
    on:
      repo: khj2872/Bookshop_Front
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hykang2872@gmail.com